// <auto-generated />
using System;
using IT_Project2526;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IT_Project2526.Migrations
{
    [DbContext(typeof(ITProjectDB))]
    [Migration("20251018214807_IntialCreate")]
    partial class IntialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IT_Project2526.Models.Customer", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CreatorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("IT_Project2526.Models.Employee", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("IT_Project2526.Models.Project", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionTarget")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectManagerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.HasIndex("ProjectManagerGuid");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("IT_Project2526.Models.Resource", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CreatorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.HasIndex("ProjectGuid");

                    b.ToTable("Resources");
                });

            modelBuilder.Entity("IT_Project2526.Models.Ticket", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletionDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletionTarget")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatorGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CustomerGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ParentTicketGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProjectGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TicketStatus")
                        .HasColumnType("int");

                    b.Property<int?>("TicketType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Guid");

                    b.HasIndex("CustomerGuid");

                    b.HasIndex("ParentTicketGuid");

                    b.HasIndex("ProjectGuid");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("IT_Project2526.Models.Project", b =>
                {
                    b.HasOne("IT_Project2526.Models.Employee", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("IT_Project2526.Models.Resource", b =>
                {
                    b.HasOne("IT_Project2526.Models.Project", null)
                        .WithMany("Resources")
                        .HasForeignKey("ProjectGuid");
                });

            modelBuilder.Entity("IT_Project2526.Models.Ticket", b =>
                {
                    b.HasOne("IT_Project2526.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerGuid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IT_Project2526.Models.Ticket", "ParentTicket")
                        .WithMany("SubTickets")
                        .HasForeignKey("ParentTicketGuid");

                    b.HasOne("IT_Project2526.Models.Project", null)
                        .WithMany("Tasks")
                        .HasForeignKey("ProjectGuid");

                    b.Navigation("Customer");

                    b.Navigation("ParentTicket");
                });

            modelBuilder.Entity("IT_Project2526.Models.Project", b =>
                {
                    b.Navigation("Resources");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("IT_Project2526.Models.Ticket", b =>
                {
                    b.Navigation("SubTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
